### ISSUE TITLE
CPU temp is not correct 

### ISSUE THREAD

**Issue by sdli1995** [v-svg/dde-dock-netspeed#1]
you read temp from this file that may not a correct temp file for cpu. you'd better to judge device name which equal to "coretemp" in those hwmon folders 
https://github.com/v-svg/dde-dock-netspeed/blob/a5de706e54406cb9b470194453a2173ab2f77154/netspeedplugin.cpp#L210
in my case hwmon0 is AC which dose not have temp file ,the correct hwmon folder for cpu is hwmon5

**Comment by v-svg** [comment]
I added new file paths for CPU temperature and frequency  https://github.com/v-svg/dde-dock-netspeed/commit/afa754f9b20d689fdfa529c4ab3fba15d3c02be3. Check now if temperature is displayed correctly.

**Comment by sdli1995** [comment]
it's works good ,thanks

**Comment by lsdustc** [comment]
nice work
