### ISSUE TITLE
Display both Download and Upload speeds?

### ISSUE THREAD

**Issue by rdlf4** [v-svg/dde-dock-netspeed#4]
Hello there.
I've tried your Deepin applet with UbuntuDDE, it works great, but it only shows the Download speed.
Thing is, it also shows Upload speed but using the same indicator. I can't differentiate which speed it's reporting sometimes. Clicking on the applet shows me each speed, but that's a little inconvenient. I work with remote desktop and sometimes my computer is accessed by my manager. I'm relying on this applet to let me know my Upload speed.
Is there anything or any tweak I can do in order to get speed rates for both?

TIA.

**Comment by v-svg** [comment]
Hello.  As you already noticed, the indicator shows the download speed or the upload speed by choosing the highest of them.  To change the display, you need to edit the source code.  You can also download a widget with two separate indicators: https://github.com/sonichy/CMDU_DDE_DOCK
